server {
    listen 80;
    server_name _;

    # Konfigurasi dasar untuk file React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Penting untuk React Router (SPA) agar melempar error 404 kembali ke index.html
        try_files $uri $uri/ /index.html;
    }

    # Proxy untuk rute /api ke backend Go
    # Agar frontend tidak terkena CORS dan menggunakan domain yang sama
    location /api/ {
        # rekammedis_backend adalah nama container dari backend Go di docker-compose
        proxy_pass http://rekammedis_backend:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
