# Server untuk Web Frontend (ArummyFisio)
server {
    listen 80;
    server_name arummyfisio.valuesstech.my.id _;

    # Konfigurasi dasar untuk file React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Penting untuk React Router (SPA) agar melempar error 404 kembali ke index.html
        try_files $uri $uri/ /index.html;
    }

    # Proxy internal (opsional tapi bagus untuk hindari CORS)
    location /api/ {
        proxy_pass http://rekammedis_backend:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Server khusus untuk Backend / Mobile App (Berekam)
server {
    listen 80;
    server_name berekam.valuesstech.my.id;

    location / {
        proxy_pass http://rekammedis_backend:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
